// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCK4LrXIKgWuuUYhg6aBvXOwL2iYkKxYaw',
    appId: '1:107765450288:web:8e933fde0e3187b15a0ff5',
    messagingSenderId: '107765450288',
    projectId: 'tiktok-clone-app-91993',
    authDomain: 'tiktok-clone-app-91993.firebaseapp.com',
    storageBucket: 'tiktok-clone-app-91993.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAyFbXGirMPdJSQUJ-Kz4gq1H7tZSRE1I',
    appId: '1:107765450288:android:c44a69f3d4aa07455a0ff5',
    messagingSenderId: '107765450288',
    projectId: 'tiktok-clone-app-91993',
    storageBucket: 'tiktok-clone-app-91993.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPhuxzgfLAf5TgRSxF4J7L8mTQMtBS_Wc',
    appId: '1:107765450288:ios:f850463d720be2545a0ff5',
    messagingSenderId: '107765450288',
    projectId: 'tiktok-clone-app-91993',
    storageBucket: 'tiktok-clone-app-91993.appspot.com',
    iosBundleId: 'com.example.flutterUlearningApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPhuxzgfLAf5TgRSxF4J7L8mTQMtBS_Wc',
    appId: '1:107765450288:ios:f850463d720be2545a0ff5',
    messagingSenderId: '107765450288',
    projectId: 'tiktok-clone-app-91993',
    storageBucket: 'tiktok-clone-app-91993.appspot.com',
    iosBundleId: 'com.example.flutterUlearningApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCK4LrXIKgWuuUYhg6aBvXOwL2iYkKxYaw',
    appId: '1:107765450288:web:1abc731b10336c6d5a0ff5',
    messagingSenderId: '107765450288',
    projectId: 'tiktok-clone-app-91993',
    authDomain: 'tiktok-clone-app-91993.firebaseapp.com',
    storageBucket: 'tiktok-clone-app-91993.appspot.com',
  );
}
